name: "GLG Know Screamer"
description: "Provides validation for GLG Know Portal"
author: Magno West
inputs:
  token:
    description: Should be secrets.GITHUB_TOKEN
    required: true
runs:
  using: "node12"
  main: "index.js"
